sudo: required
services:
- docker
script:
- sh tools/bin/build.sh
deploy:
  provider: s3
  access_key_id:
    secure: Vibf7S/SYavLur0GYdl9Wna6C7s0jeW1P3R+oknz1MpZAXWrF5esm0+EDEdrt04XOn6RYrrKFgQ4n7THzw6n484xv037mMP/XxjF8sQwkQwF3s2e3PdybT5zJthGHYeQb7vdxB/eJlFhloOvya4H6wApH1X7uLBoUWycz9DJeruNjBPX+TXLVBIcGELXoxf4ArT7Of8llzHq1RWU37JxthQzuHALbIJWNgaAmFdSxuJIMu30J8jg5jhAeQaib+F5F6B+69N/4CnsyC8pELEafpUDBYQopNTtTKofVaImogTk8Je8+y/O8wbrVpAiza53tpKSD2aiY/mytg6f1ye4M+AtQoMNgWmTDaDBBlVpop0dQlRLCtssEr24XRUxvKDhQSYZEnUCeh9z1CEvbZWLgetscAS62z3XMBRclxh2riLjrpNzylJN20HilMSG+D+YKqGywJEHkkhLklCMhclVzxAonA3kE+YorJQRcwa65V3olRYlvDBv/K1tret5ZsxxxzDXrMy2Soz2fejnwOoZEsQ4P3KQTc827TeVK354ZatLsVaYKmHSmLbd4OBTcLqkVUtVMHXrdpCjwM0WzvwkJDwVV95o+RQpl9rgwQUhFR9hCUXPTmBPfzgQybKG4ztFWhrUQM/X0Q2x/yJYTqNAQDGp5PoKnPpSVVbuU2PY6yg=
  secret_access_key:
    secure: InY/vB3ozi2zN73+8sh8gPCRnmxaQBuwyRYxL2JmCKIwEyCe7b38AJvXxJaKSELU7FtdILmIcLgj724UgGmdpCBCCmGiqEWfKxA1vcNQHwhY6v3Ho9+OtmA20A+gm8ruEKXYHHzmR/91ZhTBEsKkWGC7tjjqyL4zBnD/NyUFoMo4BLlp9E38UkUqMXTGc+HVTqFKxmABhQOmxPETSrLCws/c0914CwVuNwdtbWR41iO93YluQ41KThIhJHr4cTqSEiFVYe6opxuCmDtFuD4jrUOZSeMqe5ztlPuxUyJscFlecRfDPr1p4SwXMoKp/G0fPktYpiCmfVbzNAYAPKX2sVMt9wHd9QknER8aQoJ6Kl0Z3cM1dkw+ArKstOvpLqaxE/GGVmCm2gh3IdHWhU44FVCwebQphlL08JuDsHW2pPI7ihtrjg8POH2fE1YhrCNKm9AopglgzdkEcD8iuRz8KUqLfeOL96rrIhzTket+1996rx0udEDHZ7kyhrB1XqdwF9Y4fLFrVohEolBakFGQ4TiVd7GyuXB1+kBW4PZ/fBDXw6Cb837F7xQJEksuPPUhHcHBPukY+QM9YqWtPn3Mk657MysiEdI7R5RUUWB2tsbJZpsKTKY1dq4cCiot4OmQPg6DnLO2Bhg77lYEgeE5gf/rFNVFEEx9Y92PMc/kngk=
  bucket:
    secure: kuHCu3sUDApMyeJSaI11ODJ6SNWciaV/CrhACMnj1znC7LGHllSQVAkwGCL19cwsdvy3l1JGUubutI7DOZ7O971dLrYvKbM9LlGwbz9t5eccvqwvFzFGlP2KiyvJPqE2OnkezChIV3nzdtZF4fUz0PvgQOAPSYrEoC1HeRUK+FgDrKOwlIJ+AXv6TrMk0qZSXKi6REVHD9JUAqSB9F+fj73ZLlVn5m/WSJ0UhqEOsTmcwzEEwdni7+uIgDPedPrnfKGCaCY69fBy3n5c3M27DoD+yUgEShyyPUDdrBc5J7He95VP512CLWH4L7Xu+jgLpQZnQQkp6iPoJXATHyU67VdOrNgmyqcP9zVQ4krCPmkeeDCtntZuw1lQXXCHe6qU0l9Qvpx3sJ/nJXi1R/yVvyoMw7aRgxhY3JZViq/sb1PfVYoLvnrbV5b/Ejyq/gCCgrqwQpaWQfQttkb/OFSsDa/IsJ4SzXmwHd0cl22T2u9jiM6cFvJsoYJK/xflLNDOHv4rSpPAOlRpVypQbVKki7tDq4hNuJSPGhWJ0fBY27XZkBHS5tRlpJXasb3zjzEDNXO1QzOVMle8uZyR4/uHATJN0qy4UNcAaXV09e4OdRNCInckHGP71QOZX+8uZ6phrcYpOmr20Sm6i09j78k3RxV4wWDsnJoBisrF2ykRXng=
  region: eu-west-1
  local-dir: target/site
  upload-dir: pracc
  acl: public_read
  skip_cleanup: true
  on:
    repo: OpenPEPPOL/pracc-esens
    branch: master
